### ISSUE TITLE
Silex 2 and profiling

### ISSUE THREAD

**Issue by jeromemacias** [pomm-project/pomm-service-provider#1]
I forked the project and made 2 modifications:
- converted `PommServiceProvider` to Silex 2 requirements
- added `PommProfilerServiceProvider`

Here is my fork: https://github.com/jeromemacias/pomm-service-provider
I can't do a simple PR.

For the Silex 2 conversion, I think we need to create a 1.0 branch containing the current master.
The new master could contain the provider working with Silex 2.

For the `PommProfilerServiceProvider`, I don't know if it's better to create a new repository.

What do you think ?

**Comment by chanmix51** [comment]
First of all, thank you for the great work :+1: 

Imho that'd be great if the profiler job could be shared with a sf2 bundle, I don't really know how we de that yet. 

ping @Sanpi ?

**Comment by jeromemacias** [comment]
We can only share the view and eventually a listener (none in our case) of the profiler with a sf2 bundle.

See the https://github.com/silexphp/Silex-WebProfiler for an example.

**Comment by chanmix51** [comment]
I will have a look as soon as I get back from sfCon.

**Comment by chanmix51** [comment]
ok, I did create a « silex-1 » branch, the master will be devoted to Silex2, you can submit a PR against master :+1:

**Comment by jeromemacias** [comment]
From the sf2 bundle, we can also share the `DatabaseDataCollector`.

**Comment by chanmix51** [comment]
I must say I am pleased by the quality of your PR. Thank you very much for your job.
