### ISSUE TITLE
Installation branch silex-1

### ISSUE THREAD

**Issue by Hadrien45** [pomm-project/pomm-service-provider#5]
Hi, 

I try to install pomm-service-provider with Silex 1.3, I follow the README file but composer return this error:
 Problem 1
    - Installation request for pomm-project/pomm-service-provider dev-master -> satisfiable by pomm-project/pomm-service-provider[dev-master].
    - pomm-project/pomm-service-provider dev-master requires silex/silex ~2.0@dev -> no matching package found.

Thanks.

**Comment by sanpii** [comment]
For silex 1, use the `silex-1` branch.

You can see this [composer.json](https://github.com/sanpii/spore/blob/pomm2/composer.json) as example.

**Comment by Hadrien45** [comment]
Thank you very much. 
The readme file in branch "silex-1" indicate "dev-master" instead of "dev-silex-1".
